version: '3.8'

services:
  go-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your_jwt_secret
      - PORT=127.0.0.1:8080
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"